<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Rizqy Amelia Zein">
  <meta name="dcterms.date" content="2026-04-10">
  <title>Statistik dalam Penelitian Psikologi – Regresi Logistik Binomial</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b88fc607bb0f0970b04a6010b14008f9.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Regresi Logistik Binomial</h1>
  <p class="subtitle">Statistik dalam Penelitian Psikologi</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rizqy Amelia Zein 
</div>
        <p class="quarto-title-affiliation">
            <a href="https://psikologi.unair.ac.id/dosen-rizqy-amelia-zein/"><em>Departemen Psikologi, Universitas Airlangga</em></a>
          </p>
        <p class="quarto-title-affiliation">
            <a href="https://www.cais-research.de/team/rizqy-amelia-zein/">Research Data &amp; Methods Team, Center for Advanced Internet Studies</a>
          </p>
    </div>
</div>

  <p class="date">2026-04-10</p>
</section>
<section id="outline" class="slide level2">
<h2><em>Outline</em></h2>
<ul>
<li>Mengapa regresi linear tidak bisa digunakan untuk <em>outcome</em> biner?</li>
<li>Rantai konsep: probabilitas, <em>odds</em>, <em>log odds</em>, dan <em>odds ratio</em></li>
<li>Persamaan model &amp; interpretasi koefisien</li>
<li>Estimasi model: <em>Maximum Likelihood</em> dan uji <em>fit</em></li>
<li>Model dengan banyak prediktor</li>
<li>Asumsi regresi logistik</li>
<li>Evaluasi akurasi prediksi</li>
<li>Pelaporan hasil</li>
</ul>
</section>
<section>
<section id="variabel-biner-dalam-penelitian-psikologi" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Variabel biner dalam penelitian psikologi</h1>

</section>
<section id="outcome-biner-ada-di-berbagai-konteks" class="slide level2">
<h2><em>Outcome</em> biner ada di berbagai konteks</h2>
<ul>
<li class="fragment"><strong>Putus studi PJJ:</strong> Sepertiga mahasiswa PJJ tidak menyelesaikan studinya sebelum semester kelima (<a href="https://press.uchicago.edu/ucp/books/book/chicago/L/bo3630345.html">Tinto, 1987</a>; [Park &amp; Choi, 2009(https://www.jstor.org/stable/jeductechsoci.12.4.207)])</li>
<li class="fragment"><strong>Relapse gangguan kecemasan:</strong> 40–60% pasien mengalami kekambuhan dalam jangka panjang setelah remisi (<a href="https://psychiatryonline.org/doi/full/10.1176/appi.ajp.162.6.1179">Bruce et al., 2005</a>)</li>
<li class="fragment"><strong>Turnover karyawan:</strong> 15–20% per tahun dianggap normal; di atas angka itu menandakan masalah organisasi (SHRM, 2023)</li>
<li class="fragment"><strong>Percobaan bunuh diri:</strong> Sekitar 2.4% prajurit militer AS melakukan percobaan bunuh diri dalam satu tahun (<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4860903/">Kessler et al., 2014</a>)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><em>Outcome</em> ini bukan skor 1–100 (data <em>continous</em>). Mereka adalah <strong>keputusan biner</strong>: terjadi (1) atau tidak terjadi (0). Kita membutuhkan metode statistik yang dirancang untuk memodelkan <strong>probabilitas</strong> kejadian seperti ini.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="mengapa-bukan-regresi-linear" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Mengapa bukan regresi linear?</h1>

</section>
<section id="regresi-linear-menghasilkan-prediksi-yang-mustahil" class="slide level2">
<h2>Regresi linear menghasilkan prediksi yang mustahil</h2>
<p>Misalnya kita ingin memprediksi <strong>putus studi mahasiswa PJJ</strong> berdasarkan jarak ke kelompok belajar (pokjar):</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 40%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Mahasiswa</th>
<th style="text-align: center;">Jarak ke pokjar</th>
<th style="text-align: center;">Prediksi P(putus studi) dengan OLS</th>
<th style="text-align: center;">Valid?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: center;">5 km</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">✓</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: center;">50 km</td>
<td style="text-align: center;"><strong>1.45</strong></td>
<td style="text-align: center;">✗</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: center;">0 km</td>
<td style="text-align: center;"><strong>−0.10</strong></td>
<td style="text-align: center;">✗</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Masalah fundamental:</strong> Probabilitas harus berada di rentang 0 sampai 1. Regresi linear tidak menjamin ini — ia memodelkan hubungan linear tanpa batas (∞).</li>
<li><strong>Yang dibutuhkan:</strong> Sebuah fungsi yang secara otomatis <em>membatasi</em> prediksi dalam rentang [0, 1].</li>
</ul>
</section>
<section id="solusi-fungsi-logistik-kurva-s" class="slide level2">
<h2>Solusi: fungsi logistik (kurva S)</h2>
<p><span class="math display">\[P = \frac{1}{1 + e^{-(\beta_0 + \beta_1 X)}}\]</span></p>
<p>Tiga sifat penting kurva S (<em>sigmoid</em>):</p>
<ul>
<li class="fragment"><strong>Asimptot bawah = 0</strong> — probabilitas tidak pernah negatif</li>
<li class="fragment"><strong>Asimptot atas = 1</strong> — probabilitas tidak pernah melampaui 1</li>
<li class="fragment"><strong>Transisi halus di bagian tengah</strong> — perubahan probabilitas melambat di ujung-ujungnya</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Rentang <em>outcome</em> selalu 0-1 meskipun prediktor nilainya ekstrim</strong></p>
</div>
<div class="callout-content">
<p>Tidak peduli seberapa ekstrim nilai prediktor (X), probabilitas yang diprediksi <strong>tetap berada dalam rentang yang valid</strong>. Inilah keunggulan utama regresi logistik dibanding OLS untuk <em>outcome</em> biner.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="rantai-konsep-p-odds-log-odds-odds-ratio" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Rantai konsep: P → <em>Odds</em> → <em>Log Odds</em> → <em>Odds Ratio</em></h1>

</section>
<section id="probabilitas-titik-awal-yang-sudah-kita-kenal" class="slide level2">
<h2>Probabilitas — titik awal yang sudah kita kenal</h2>
<p><span class="math display">\[P(A) = \frac{\text{jumlah kejadian A}}{\text{total kemungkinan}}\]</span></p>
<p><strong>Contoh dari dataset PJJ (N = 450):</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 39%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Konteks</th>
<th style="text-align: center;">Probabilitas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>135 dari 450 mahasiswa putus studi sebelum semester ke-5</td>
<td style="text-align: center;">P(putus studi) = 0.30</td>
</tr>
<tr class="even">
<td>8 dari 200 mahasiswa pernah mencoba bunuh diri</td>
<td style="text-align: center;">P(percobaan) = 0.04</td>
</tr>
<tr class="odd">
<td>60 dari 200 karyawan <em>resign</em> dalam 1 tahun</td>
<td style="text-align: center;">P(turnover) = 0.30</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Regresi logistik memodelkan <em>log odss</em></strong></p>
</div>
<div class="callout-content">
<p>Regresi logistik <strong>tidak memodelkan P secara langsung</strong> — ia memodelkan transformasinya, yaitu <em>log odds</em>. Mengapa? Karena probabilitas tidak linear, sementara <em>log odds</em> bisa diperlakukan sebagai linear terhadap prediktor.</p>
</div>
</div>
</div>
</section>
<section id="odds-berapa-kali-lebih-mungkin-terjadi-dibanding-tidak-terjadi" class="slide level2">
<h2><em>Odds</em> — “berapa kali lebih mungkin terjadi dibanding tidak terjadi”</h2>
<p><span class="math display">\[\text{Odds} = \frac{P}{1 - P}\]</span></p>
<p><strong>Contoh:</strong> Jika P(putus studi) = 0.30, maka Odds = 0.30 / 0.70 = <strong>0.43</strong></p>
<p>Cara baca: “Untuk setiap 7 mahasiswa yang bertahan, ada 3 yang putus studi” (3:7)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">P(kejadian)</th>
<th style="text-align: center;">Odds</th>
<th>Cara baca</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.11</td>
<td>1 banding 9</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.33</td>
<td>1 banding 3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td>Sama rata</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">3.00</td>
<td>3 banding 1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">9.00</td>
<td>9 banding 1</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpretasi <em>odds</em></strong></p>
</div>
<div class="callout-content">
<p>Odds = 1 artinya peluang terjadi <strong>sama dengan</strong> tidak terjadi. Odds &gt; 1 artinya lebih mungkin terjadi; Odds &lt; 1 artinya lebih tidak mungkin.</p>
</div>
</div>
</div>
</section>
<section id="log-odds-logit-membuat-odds-simetris-dan-linear" class="slide level2">
<h2><em>Log odds</em> (logit) — membuat <em>odds</em> simetris dan linear</h2>
<p><strong>Masalah <em>odds</em>:</strong> Rentangnya 0 sampai ∞, dan tidak simetris — nilai di bawah 1 terkompresi, nilai di atas 1 tidak terbatas.</p>
<p><strong>Solusi: <em>Log odds</em> (logit)</strong></p>
<p><span class="math display">\[\text{Logit}(P) = \ln\!\left(\frac{P}{1-P}\right)\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">P</th>
<th style="text-align: center;"><em>Odds</em></th>
<th style="text-align: center;"><em>Logit</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">−2.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">−1.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">3.00</td>
<td style="text-align: center;">+1.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">9.00</td>
<td style="text-align: center;">+2.20</td>
</tr>
</tbody>
</table>
<p>Perhatikan: <em>logit</em> simetris di sekitar 0 dan rentangnya −∞ sampai +∞. <strong>Inilah yang dimodelkan secara linear</strong> oleh regresi logistik.</p>
</section>
<section id="persamaan-model-regresi-logistik" class="slide level2">
<h2>Persamaan model regresi logistik</h2>
<p><strong>Persamaan dalam <em>logit</em> (yang berjalan di belakang layar):</strong></p>
<p><span class="math display">\[\ln\!\left(\frac{P}{1-P}\right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_k X_k\]</span></p>
<p><strong>Untuk memprediksi probabilitas, balik transformasinya:</strong></p>
<p><span class="math display">\[P = \frac{1}{1 + e^{-(\beta_0 + \beta_1 X_1 + \cdots + \beta_k X_k)}}\]</span></p>
<p><strong>Komponen:</strong></p>
<ul>
<li>β₀ = <em>intercept</em> (<em>log odds</em> ketika semua prediktor = 0)</li>
<li>β₁, …, βₖ = koefisien regresi (perubahan <em>logit</em> per satu unit prediktor)</li>
<li><strong>e^β = <em>Odds Ratio</em></strong> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <strong>inilah yang diinterpretasikan dalam sebagai <em>effect size</em> dari regresi logistik</strong></li>
</ul>
</section>
<section id="odds-ratio-or-ukuran-efek-utama" class="slide level2">
<h2><em>Odds Ratio</em> (OR) — ukuran efek utama</h2>
<p><span class="math display">\[OR = e^{\beta}\]</span></p>
<p>OR mengukur seberapa banyak <em>odds</em> berubah ketika prediktor naik 1 unit, dengan prediktor lain dikontrol.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">OR</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">= 1.00</td>
<td>Tidak ada efek</td>
</tr>
<tr class="even">
<td style="text-align: center;">&gt; 1.00</td>
<td><em>Odds</em> <em>outcome</em> <strong>naik</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">&lt; 1.00</td>
<td><em>Odds</em> <em>outcome</em> <strong>turun</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">= 1.50</td>
<td><em>Odds</em> naik 50%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">= 2.00</td>
<td><em>Odds</em> naik 100% (dua kali lipat)</td>
</tr>
<tr class="even">
<td style="text-align: center;">= 0.50</td>
<td><em>Odds</em> turun 50% (setengahnya)</td>
</tr>
</tbody>
</table>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Selalu laporkan 95% <em>Confidence Interval</em> untuk OR!</strong></p>
</div>
<div class="callout-content">
<p>Jika CI melewati 1.0, prediktor tidak signifikan secara statistik — misalnya OR = 1.20, 95% CI [0.85, 1.69] → tidak signifikan.</p>
</div>
</div>
</div>
</section>
<section id="studi-kasus-apa-yang-memprediksi-putus-studi-pjj" class="slide level2">
<h2>Studi kasus: apa yang memprediksi putus studi PJJ?</h2>
<p><strong>Konteks:</strong> 450 mahasiswa PJJ; 30% putus studi sebelum semester ke-5</p>
<p><strong>Prediktor:</strong> Jarak ke pokjar, keterlibatan akademik, kecemasan akademik awal</p>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Prediktor</th>
<th style="text-align: center;">β</th>
<th style="text-align: center;">OR</th>
<th>95% CI</th>
<th style="text-align: center;">p</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jarak (per 10 km)</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">1.63</td>
<td>[1.21, 2.19]</td>
<td style="text-align: center;">&lt;.001</td>
<td>Jarak +10 km → <em>odds</em> +63%</td>
</tr>
<tr class="even">
<td>Keterlibatan akademik</td>
<td style="text-align: center;">−0.65</td>
<td style="text-align: center;">0.52</td>
<td>[0.38, 0.71]</td>
<td style="text-align: center;">&lt;.001</td>
<td>Keterlibatan ↑ → <em>odds</em> −48%</td>
</tr>
<tr class="odd">
<td>Kecemasan akademik</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">1.02</td>
<td>[0.99, 1.05]</td>
<td style="text-align: center;">.182</td>
<td>Tidak signifikan</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpretasi</strong></p>
</div>
<div class="callout-content">
<p>Keterlibatan akademik yang tinggi dapat “<strong>mencegah</strong>” efek jarak yang jauh antara tempat tinggal mahasiswa dengan pokjar. Bisa dijadikan dasar untuk mendesain intervensi program PJJ.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="estimasi-fit-model" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Estimasi &amp; <em>Fit</em> Model</h1>

</section>
<section id="maximum-likelihood-estimation-mle" class="slide level2">
<h2><em>Maximum Likelihood Estimation</em> (MLE)</h2>
<p><strong>Regresi linear (OLS):</strong></p>
<p>Cari β yang <strong>meminimalkan</strong> jumlah kuadrat <em>error</em> (SSE)</p>
<p><strong>Regresi logistik (MLE):</strong></p>
<p>Cari β yang membuat variabel <em>outcome</em> yang kita observasi <strong>“paling mungkin terjadi”</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mengapa MLE</strong></p>
</div>
<div class="callout-content">
<p>Karena MLE, kita <strong>tidak mendapatkan F-statistic</strong> seperti dalam OLS/ANOVA. Sebagai gantinya, kita mendapatkan <strong>χ²</strong> sebagai uji signifikansi keseluruhan model.</p>
<p>Jika <em>software</em> menampilkan peringatan <em>Algorithm did not converge</em> — biasanya tanda sampel terlalu kecil atau ada <em>perfect separation</em> (lihat bagian berikutnya).</p>
</div>
</div>
</div>
</section>
<section id="deviance-likelihood-ratio-test-uji-omnibus-model" class="slide level2">
<h2><em>Deviance</em> &amp; <em>Likelihood Ratio Test</em> — uji omnibus model</h2>
<p><strong>Deviance</strong> = −2 × <em>log-likelihood</em> (makin kecil, makin baik)</p>
<table class="caption-top">
<colgroup>
<col style="width: 10%">
<col style="width: 57%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><em>Deviance</em></th>
<th>Arti</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Null deviance</strong></td>
<td style="text-align: center;">612.4</td>
<td>Model tanpa prediktor — “tebakan terbaik tanpa informasi”</td>
</tr>
<tr class="even">
<td><strong>Residual deviance</strong></td>
<td style="text-align: center;">487.2</td>
<td>Model dengan prediktor kita</td>
</tr>
<tr class="odd">
<td><strong>Penurunan</strong></td>
<td style="text-align: center;"><strong>125.2</strong></td>
<td>Bukti bahwa prediktor berguna</td>
</tr>
</tbody>
</table>
<p><strong>Likelihood Ratio Test:</strong></p>
<p><span class="math display">\[\chi^2 = \text{Null deviance} - \text{Residual deviance}\]</span></p>
<p><span class="math display">\[\chi^2(3) = 125.2,\ p &lt; .001 \rightarrow \text{Model secara keseluruhan signifikan!}\]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Uji Omnibus</strong></p>
</div>
<div class="callout-content">
<p>Ini adalah <strong>uji omnibus</strong> — setara dengan uji F keseluruhan dalam regresi linear. Di jamovi, angka ini muncul di bagian <em>Model Fit</em> sebagai <strong>Model χ²</strong>.</p>
</div>
</div>
</div>
</section>
<section id="aic-bic-memilih-model-terbaik" class="slide level2">
<h2>AIC &amp; BIC — memilih model terbaik</h2>
<p>Prinsipnya sama dengan regresi OLS yang sudah kita pelajari di Bagian 3: menambah prediktor <strong>selalu</strong> menurunkan <em>deviance</em>, bahkan jika prediktor itu tidak bermakna (<em>overfitting</em>).</p>
<p><span class="math display">\[\text{AIC} = -2\log L + 2k \qquad \text{BIC} = -2\log L + k\ln(n)\]</span></p>
<p>Di mana k = jumlah parameter, n = ukuran sampel. <strong>Makin kecil, makin baik — hanya bermakna untuk membandingkan model.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th>Prediktor</th>
<th style="text-align: center;">AIC</th>
<th style="text-align: center;">BIC</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 1</td>
<td>Jarak saja</td>
<td style="text-align: center;">502.1</td>
<td style="text-align: center;">510.3</td>
<td></td>
</tr>
<tr class="even">
<td>Model 2</td>
<td>Jarak + Keterlibatan</td>
<td style="text-align: center;">489.7</td>
<td style="text-align: center;">502.1</td>
<td>← Terbaik</td>
</tr>
<tr class="odd">
<td>Model 3</td>
<td>Jarak + Keterlibatan + Usia + Gender</td>
<td style="text-align: center;">493.2</td>
<td style="text-align: center;">518.9</td>
<td></td>
</tr>
</tbody>
</table>
<p>Model 2 menang: <em>fit</em> bagus tanpa terlalu kompleks. BIC lebih ketat dari AIC karena penaltinya lebih besar — pilih BIC jika prioritasnya parsimoni.</p>
</section>
<section id="pseudo-r²-seberapa-banyak-variasi-yang-dijelaskan" class="slide level2">
<h2>Pseudo R² — seberapa banyak variasi yang dijelaskan?</h2>
<p><strong>Masalah:</strong> Regresi logistik tidak punya R² seperti OLS karena tidak ada “total <em>variance</em>” yang bisa dibagi seperti dalam OLS.</p>
<p><strong>Solusi: Pseudo R²</strong> — ada beberapa versi, yang paling sering dilaporkan adalah <strong>Nagelkerke R²:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Nagelkerke R²</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">&lt; 0.20</td>
<td>Lemah</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.20–0.40</td>
<td>Cukup</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.40–0.60</td>
<td>Baik</td>
</tr>
<tr class="even">
<td style="text-align: center;">&gt; 0.60</td>
<td>Sangat baik</td>
</tr>
</tbody>
</table>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpretasi Pseudo R²</strong></p>
</div>
<div class="callout-content">
<p>Pseudo R² <strong>bukan</strong> “proporsi varians yang dijelaskan” seperti R² OLS, jadi jangan diinterpretasikan dengan cara yang sama! Lebih tepat diartikan sebagai “peningkatan <em>fit</em> dibanding <em>null model</em>.” Nilainya cenderung lebih rendah dari R² OLS.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="model-dengan-banyak-prediktor" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Model dengan Banyak Prediktor</h1>

</section>
<section id="adjusted-or-efek-prediktor-setelah-mengontrol-variabel-lain" class="slide level2">
<h2>Adjusted OR — efek prediktor setelah mengontrol variabel lain</h2>
<p><strong>Masalah <em>confounding</em>:</strong> Dalam analisis bivariat, efek yang terlihat bisa dipengaruhi oleh variabel ketiga.</p>
<p>Contoh: Mahasiswa yang tinggal jauh dari pokjar cenderung punya keterlibatan akademik yang lebih rendah (karena kesempatan terlibat lebih terbatas). Efek jarak dan efek keterlibatan <strong>saling tumpang tindih</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Prediktor</th>
<th style="text-align: center;"><em>Unadjusted</em> OR</th>
<th style="text-align: center;"><em>Adjusted</em> OR</th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jarak (per 10 km)</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">1.63</td>
<td>[1.21, 2.19]</td>
</tr>
<tr class="even">
<td>Keterlibatan akademik</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">0.52</td>
<td>[0.38, 0.71]</td>
</tr>
<tr class="odd">
<td>Usia (per 10 tahun)</td>
<td style="text-align: center;">1.15</td>
<td style="text-align: center;">1.08</td>
<td>[0.88, 1.32]</td>
</tr>
</tbody>
</table>
<p>Setelah dikontrol, efek jarak sedikit mengecil — sebagian efeknya bekerja <em>melalui</em> keterlibatan akademik.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Laporkan <em>Adjusted</em> OR</strong></p>
</div>
<div class="callout-content">
<p>Dalam artikel ilmiah, <strong>selalu laporkan <em>adjusted</em> OR</strong> dari model dengan prediktor berganda, bukan <em>unadjusted</em> OR dari analisis bivariat.</p>
</div>
</div>
</div>
</section>
<section id="interaksi-efek-prediktor-yang-berbeda-antar-subgrup" class="slide level2">
<h2>Interaksi — efek prediktor yang berbeda antar subgrup</h2>
<p><strong>Pertanyaan:</strong> Apakah efek jarak pada putus studi <em>berbeda</em> tergantung tingkat keterlibatan akademik?</p>
<p><span class="math display">\[\text{logit}(P) = \beta_0 + \beta_1(\text{Jarak}) + \beta_2(\text{Keterlibatan}) + \beta_3(\text{Jarak} \times \text{Keterlibatan})\]</span></p>
<p><strong>Hasil:</strong> β₃ = −0.08, p = .03 → Interaksi signifikan!</p>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 61%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Subgrup</th>
<th style="text-align: center;">Efek jarak pada <em>odds</em> putus studi</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Keterlibatan <strong>rendah</strong></td>
<td style="text-align: center;">OR = 1.12 per km</td>
<td>Jarak sangat berpengaruh</td>
</tr>
<tr class="even">
<td>Keterlibatan <strong>tinggi</strong></td>
<td style="text-align: center;">OR = 1.02 per km</td>
<td>Jarak hampir tidak berpengaruh</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Keterlibatan akademik yang tinggi bisa <strong>men-<em>buffer</em></strong> dampak jarak yang jauh, sehingga bisa dijadikan dasar untuk merancang intervensi yang tepat sasaran.</p>
</div>
</div>
</div>
</section>
<section id="strategi-membangun-model-mulai-dari-teori" class="slide level2">
<h2>Strategi membangun model — mulai dari teori</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>✅ <em>Theory-driven</em> (direkomendasikan)</strong></p>
<ol type="1">
<li>Pilih prediktor berdasarkan teori dan literatur <strong>sebelum</strong> melihat data</li>
<li>Uji hipotesis yang sudah <em>pre-specified</em></li>
<li>Laporkan <strong>semua</strong> model yang diuji — bukan hanya yang paling bagus hasilnya secara statistik</li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>⚠️ <em>Stepwise selection</em> (kontroversial)</strong></p>
<ul>
<li><em>Forward</em>: tambahkan prediktor satu per satu berdasarkan p-value</li>
<li><em>Backward</em>: mulai dari semua prediktor, hapus yang tidak signifikan</li>
<li><strong>Masalah:</strong> <em>Overfitting</em>, inflasi <em>Type I error</em>, hasil tidak <em>replicable</em></li>
</ul>
</div></div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Kapan analisis eksplorasi dibenarkan?</strong></p>
</div>
<div class="callout-content">
<p>Analisis eksplorasi boleh dilakukan untuk <em>generate</em> hipotesis, tapi <strong>harus dipisahkan</strong> dari analisis konfirmatori. Mencampur keduanya dalam satu sampel adalah salah satu bentuk <a href="https://journals.sagepub.com/doi/abs/10.1177/1948550615612150"><em>questionable research practice</em></a>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="asumsi-regresi-logistik" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Asumsi Regresi Logistik</h1>

</section>
<section id="kabar-baik-lebih-longgar-dari-ols" class="slide level2">
<h2>Kabar baik: lebih longgar dari OLS!</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Yang HARUS dipenuhi:</strong></p>
<ol type="1">
<li><em>Outcome</em> biner (variabel dependen dikotomus: 0/1)</li>
<li>Observasi independen — satu partisipan tidak mempengaruhi yang lain</li>
<li>Linearitas dalam <em>log odds</em> — prediktor kontinu harus punya hubungan linear dengan logit(P)</li>
<li>Tidak ada multikolinearitas ekstrem</li>
</ol>
</div><div class="column" style="width:45%;">
<p><strong>Yang TIDAK perlu:</strong></p>
<ul>
<li>✗ Normalitas residual</li>
<li>✗ Homoskedastisitas</li>
<li>✗ <em>Outcome</em> kontinu</li>
<li>✗ Hubungan linear antara prediktor dan P (hanya harus linear dalam <em>logit</em>)</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tetap harus dicek</strong></p>
</div>
<div class="callout-content">
<p>Meskipun lebih longgar, asumsi yang ada <strong>tetap harus dicek dan dilaporkan</strong>. Terutama multikolinearitas (dengan VIF) dan kemungkinan <em>perfect separation</em>.</p>
</div>
</div>
</div>
</section>
<section id="multikolinearitas-sudah-familiar-dari-bagian-3" class="slide level2">
<h2>Multikolinearitas — sudah familiar dari Bagian 3</h2>
<p>Cara memeriksa dan interpretasinya sama persis seperti dalam regresi OLS — gunakan <strong>VIF</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">VIF</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">&lt; 5</td>
<td>Tidak ada masalah</td>
</tr>
<tr class="even">
<td style="text-align: center;">5–10</td>
<td><em>Moderate</em> — perlu hati-hati</td>
</tr>
<tr class="odd">
<td style="text-align: center;">&gt; 10</td>
<td>Masalah serius</td>
</tr>
</tbody>
</table>
<p><strong>Contoh masalah:</strong> “Durasi studi (semester)” dan “biaya pendidikan kumulatif” — keduanya naik bersama, korelasi r = 0.95 → VIF ≈ 18 → tidak bisa diestimasi secara stabil.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Jamovi menampilkan VIF secara otomatis di <em>output</em> regresi logistik — centang <strong>Collinearity Statistics</strong> di opsi <strong>Model Coefficients</strong>.</p>
</div>
</div>
</div>
</section>
<section id="perfect-separation-ketika-prediktor-too-goood-to-be-true" class="slide level2">
<h2><em>Perfect separation</em> — ketika prediktor <em>too goood to be true</em></h2>
<p><strong>Masalah:</strong> Satu prediktor memisahkan <em>outcome</em> secara sempurna — semua Y = 1 ada di satu sisi, semua Y = 0 di sisi lain.</p>
<p><strong>Contoh:</strong> Semua mahasiswa dengan jarak &gt; 45 km putus studi (100%). Semua mahasiswa dengan jarak ≤ 45 km lanjut studi (100%).</p>
<p><strong>Akibat:</strong> Koefisien meluncur ke ±∞, <em>standard error</em> sangat besar, model tidak <em>converge</em>.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tanda-tanda di <em>output</em></strong></p>
</div>
<div class="callout-content">
<ul>
<li>Koefisien sangat besar (β &gt; 10 atau &lt; −10)</li>
<li><em>Standard error</em> sangat besar</li>
<li>Pesan “Algorithm did not converge”</li>
</ul>
<p>Jika ini terjadi, cek distribusi prediktor dan <em>outcome</em> — sering kali tanda bahwa ada <strong>kategori yang terlalu kecil</strong>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="evaluasi-akurasi-prediksi" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Evaluasi Akurasi Prediksi</h1>

</section>
<section id="confusion-matrix-dasar-evaluasi-akurasi" class="slide level2">
<h2><em>Confusion matrix</em> — dasar evaluasi akurasi</h2>
<p>Setelah model difit, gunakan <em>threshold default</em> P ≥ 0.50 → prediksi <em>outcome</em> terjadi; P &lt; 0.50 → prediksi tidak terjadi.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Prediksi: Tidak Terjadi</th>
<th style="text-align: center;">Prediksi: Terjadi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Aktual: Tidak Terjadi</strong></td>
<td style="text-align: center;">240 <strong>(TN)</strong></td>
<td style="text-align: center;">30 <strong>(FP)</strong></td>
</tr>
<tr class="even">
<td><strong>Aktual: Terjadi</strong></td>
<td style="text-align: center;">50 <strong>(FN)</strong></td>
<td style="text-align: center;">130 <strong>(TP)</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>TP</strong> (<em>True Positive</em>): Prediksi terjadi → aktual terjadi ✓</li>
<li><strong>TN</strong> (<em>True Negative</em>): Prediksi tidak terjadi → aktual tidak terjadi ✓</li>
<li><strong>FP</strong> (<em>False Positive</em>): Prediksi terjadi → aktual tidak terjadi ✗ (<em>false alarm</em>)</li>
<li><strong>FN</strong> (<em>False Negative</em>): Prediksi tidak terjadi → aktual terjadi ✗ (<em>miss</em> — sering yang paling berbahaya)</li>
</ul>
</section>
<section id="sensitivity-specificity-dan-akurasi" class="slide level2">
<h2><em>Sensitivity</em>, <em>specificity</em>, dan akurasi</h2>
<p>Dari <em>confusion matrix</em> tadi (TP=130, TN=240, FP=30, FN=50, N=450):</p>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Metrik</th>
<th>Formula</th>
<th style="text-align: center;">Nilai</th>
<th>Pertanyaan yang dijawab</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Akurasi</strong></td>
<td>(TP+TN)/N</td>
<td style="text-align: center;">82.2%</td>
<td>Berapa % prediksi yang benar?</td>
</tr>
<tr class="even">
<td><strong>Sensitivity</strong></td>
<td>TP/(TP+FN)</td>
<td style="text-align: center;">72.2%</td>
<td>Dari yang benar-benar terjadi, berapa % terdeteksi?</td>
</tr>
<tr class="odd">
<td><strong>Specificity</strong></td>
<td>TN/(TN+FP)</td>
<td style="text-align: center;">88.9%</td>
<td>Dari yang tidak terjadi, berapa % diprediksi benar?</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Trade-off <em>sensitivity</em> vs <em>specificity</em></strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Screening risiko bunuh diri</strong> → prioritaskan <em>sensitivity</em> tinggi — lebih baik <em>over-identify</em> daripada ada yang terlewat</li>
<li><strong>Diagnosis klinis formal</strong> → prioritaskan <em>specificity</em> tinggi — <em>false positive</em> berdampak stigma dan biaya</li>
</ul>
<p><em>Default threshold</em> = 0.50 — bisa disesuaikan sesuai konteks dan pertimbangan etis.</p>
</div>
</div>
</div>
</section>
<section id="auc-ringkasan-performa-model-dalam-satu-angka" class="slide level2">
<h2>AUC — ringkasan performa model dalam satu angka</h2>
<p><strong>AUC</strong> (<em>Area Under the ROC Curve</em>) = probabilitas bahwa model memberikan <em>predicted probability</em> yang lebih tinggi kepada kasus positif dibanding kasus negatif yang diambil secara acak.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">AUC</th>
<th style="text-align: left;">Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: left;">Tidak lebih baik dari tebakan</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.60–0.70</td>
<td style="text-align: left;">Lemah</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.70–0.80</td>
<td style="text-align: left;">Cukup</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.80–0.90</td>
<td style="text-align: left;">Baik</td>
</tr>
<tr class="odd">
<td style="text-align: center;">&gt; 0.90</td>
<td style="text-align: left;">Sangat baik — atau <em>overfitting</em>? Cek dulu!</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>ROC <em>curve</em> dan AUC tersedia di jamovi. Untuk pembahasan lebih dalam tentang ROC, Anda bisa membaca materi terpisah di <a href="https://hackmd.io/@ameliazein/roc">hackmd.io/<span class="citation" data-cites="ameliazein/roc">@ameliazein/roc</span></a>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="pelaporan-hasil" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Pelaporan Hasil</h1>

</section>
<section id="checklist-pelaporan-regresi-logistik" class="slide level2">
<h2>Checklist pelaporan regresi logistik</h2>
<p>☐ <strong>Deskripsi variabel</strong> — <em>outcome</em> biner (0/1), distribusi prediktor</p>
<p>☐ <strong>Uji signifikansi model</strong> — Model χ², df, p (dari <em>Likelihood Ratio Test</em>)</p>
<p>☐ <strong>Pseudo R²</strong> — Nagelkerke R²</p>
<p>☐ <strong>Koefisien per prediktor</strong> — β, <em>SE</em>, Wald χ², p, <strong>OR</strong>, <strong>95% CI</strong></p>
<p>☐ <strong>Multikolinearitas</strong> — VIF</p>
<p>☐ <strong>Akurasi klasifikasi</strong> — akurasi keseluruhan, <em>sensitivity</em>, <em>specificity</em></p>
<p>☐ <strong>AUC</strong> (opsional tapi dianjurkan)</p>
<p>☐ <strong>AIC/BIC</strong> jika membandingkan model</p>
</section>
<section id="contoh-paragraf-hasil" class="slide level2">
<h2>Contoh paragraf hasil</h2>
<blockquote>
<p>“Regresi logistik binomial dilakukan untuk memprediksi putus studi mahasiswa PJJ menggunakan tiga prediktor: jarak ke pokjar, kecemasan akademik awal, dan keterlibatan akademik. Model secara keseluruhan signifikan, χ²(3, <em>N</em> = 450) = 125.2, <em>p</em> &lt; .001, Nagelkerke <em>R</em>² = .32. Model berhasil mengklasifikasikan 82.2% kasus dengan benar (<em>sensitivity</em> = 72.2%, <em>specificity</em> = 88.9%, AUC = .84).</p>
<p>Jarak ke pokjar secara signifikan memprediksi putus studi (<em>OR</em> = 1.05, 95% CI [1.02, 1.08], <em>p</em> &lt; .001): setiap tambahan 10 km jarak dari pokjar, <em>odds</em> putus studi mahasiswa meningkat sebesar 63%. Keterlibatan akademik juga berperan signifikan (<em>OR</em> = 0.52, 95% CI [0.38, 0.71], <em>p</em> &lt; .001) — mahasiswa dengan keterlibatan lebih tinggi memiliki <em>odds</em> putus studi yang lebih rendah. Kecemasan akademik awal tidak memprediksi putus studi secara signifikan (<em>OR</em> = 1.02, 95% CI [0.99, 1.05], <em>p</em> = .182).”</p>
</blockquote>
</section>
<section id="menerjemahkan-or-ke-bahasa-yang-dipahami-semua-orang" class="slide level2">
<h2>Menerjemahkan OR ke bahasa yang dipahami semua orang</h2>
<p>Jangan serahkan interpretasi ke pembaca — terjemahkan OR ke kalimat yang konkrit.</p>
<p><strong>Contoh: OR = 1.05 untuk jarak ke pokjar (per 1 km)</strong></p>
<ul>
<li><p><strong>Opsi 1 — Persentase perubahan <em>odds</em>:</strong> “Setiap tambahan 1 km jarak dari pokjar, <em>odds</em> putus studi naik 5%.”</p></li>
<li><p><strong>Opsi 2 — Interval konkrit:</strong> “Mahasiswa yang tinggal 10 km lebih jauh punya <em>odds</em> putus studi 1.63 kali lebih tinggi.” <em>(karena 1.05^10 = 1.63)</em></p></li>
<li><p><strong>Opsi 3 — Perbandingan probabilitas:</strong> “Mahasiswa yang tinggal 5 km dari pokjar memiliki peluang ~20% putus studi; mahasiswa yang tinggal 15 km memiliki peluang ~30%.”</p></li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>OR ≠ <em>Risk Ratio</em> (RR).</strong> Jangan tulis “X kali lebih <em>mungkin</em>” untuk OR — itu bahasa RR. OR harus dikatakan: “X kali lebih tinggi <strong><em>odds</em></strong>-nya” (Zhang &amp; Yu, 1998, <em>JAMA</em>). Perbedaan ini penting terutama jika prevalensi <em>outcome</em> &gt; 10%.</p>
</div>
</div>
</div>
</section>
<section id="enam-kesalahan-umum" class="slide level2">
<h2>Enam kesalahan umum</h2>
<ol type="1">
<li class="fragment"><p><strong>Mengaburkan OR dengan <em>Risk Ratio</em></strong> — “X kali lebih mungkin” bukan cara yang benar untuk menginterpretasikan OR. Kata yang tepat: “X kali lebih tinggi <em>odds</em>-nya”.</p></li>
<li class="fragment"><p><strong>Mengklaim kausalitas</strong> — Regresi logistik adalah korelasional. Kausalitas membutuhkan desain eksperimental atau <em>quasi</em>-eksperimental.</p></li>
<li class="fragment"><p><strong>Mengabaikan multikolinearitas</strong> — “Usia” dan “tahun lahir” keduanya dimasukkan sebagai prediktor? Sudah pasti multikolinear.</p></li>
<li class="fragment"><p><strong>Tidak memeriksa asumsi</strong> — Terutama linearitas dalam <em>logit</em> dan kemungkinan <em>perfect separation</em>.</p></li>
<li class="fragment"><p><strong>Hanya melaporkan prediktor yang signifikan</strong> — Laporkan <strong>semua</strong> prediktor yang dimasukkan ke model — bukan <em>cherry-pick</em> yang p &lt; .05.</p></li>
<li class="fragment"><p><strong>EPV terlalu rendah</strong> — <em>Events per variable</em> (EPV): minimal 10 kejadian per prediktor. Dengan hanya 50 kejadian (<em>events</em>), jangan masukkan lebih dari 5 prediktor — estimasi akan tidak stabil.</p></li>
</ol>
</section></section>
<section>
<section id="demonstrasi-di-jamovi" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Demonstrasi di jamovi</h1>

</section>
<section id="konteks-apa-yang-memprediksi-pemberian-dukungan-sosial" class="slide level2">
<h2>Konteks: apa yang memprediksi pemberian dukungan sosial?</h2>
<ul>
<li>Dataset: <strong>Dataset Contoh Regresi Logistik</strong> (<code>dataset-social-support.omv</code>)
<ul>
<li>Dapat diunduh dari <em>navbar</em> di laman mata kuliah</li>
</ul></li>
<li>Pertanyaan penelitian berkaitan dengan faktor-faktor yang memprediksi <em>outcome</em> biner dalam konteks psikologi klinis/sosial</li>
</ul>
</section>
<section id="langkah-langkah-di-jamovi" class="slide level2">
<h2>Langkah-langkah di jamovi</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Menjalankan regresi logistik:</strong></p>
<ol type="1">
<li><strong>Analyses → Regression → Logistic Regression → 2 Outcomes (Binomial)</strong></li>
<li>Masukkan variabel <em>outcome</em> ke <strong>Dependent Variable</strong></li>
<li>Masukkan prediktor ke <strong>Covariates</strong> (kontinu) atau <strong>Factors</strong> (kategorikal)</li>
<li>Jamovi akan melakukan <em>dummy coding</em> secara otomatis untuk variabel kategorikal</li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>Output yang harus dicek:</strong></p>
<p>☑ <em>Model Fit</em> — Model χ², Nagelkerke R²</p>
<p>☑ <em>Model Coefficients</em> — β, OR, 95% CI, p</p>
<p>☑ <em>Collinearity Statistics</em> — VIF</p>
<p>☑ <em>Prediction Table</em> — akurasi, <em>sensitivity</em>, <em>specificity</em></p>
<p>☑ <em>ROC Curve</em> — AUC</p>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Urutan membaca output</strong></p>
</div>
<div class="callout-content">
<p>Omnibus (Model χ²) → Pseudo R² → Koefisien per prediktor (OR + CI) → VIF → Akurasi klasifikasi → AUC</p>
</div>
</div>
</div>
</section>
<section id="ada-pertanyaan" class="slide level2">
<h2>Ada pertanyaan❓</h2>

<img data-src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDFtaDh5ZjZ2eXJ3dmJmZmFmYzBtNHEwdzlqZmZtdGtmbnE0bXZidiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/igB2Th9e4nW6s/giphy.gif" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Paparan disusun dengan menggunakan <i class="fa-brands fa-r-project" aria-label="r-project"></i> dan <a href="https://quarto.org"><strong>Quarto</strong></a> dengan <em>template</em> dari <a href="https://github.com/rameliaz/quarto-unair-theme">UNAIR Theme</a>.</li>
<li>Kontak saya via <i class="fas fa-paper-plane"></i> <a href="mailto:amelia.zein@psikologi.unair.ac.id">amelia.zein@psikologi.unair.ac.id</a></li>
</ul>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    // Single unified function to manage all logos
    function manageLogos() {
      const slides = document.querySelectorAll('.reveal .slides section');
      
      slides.forEach(function(slide, index) {
        // Handle title slide (first slide)
        if (index === 0) {
          // Remove any regular logos from title slide
          const regularLogos = slide.querySelectorAll('.slide-logo');
          regularLogos.forEach(logo => logo.remove());
          
          // Add centered logo if it doesn't exist
          if (!slide.querySelector('.title-slide-logo')) {
            const titleLogo = document.createElement('img');
            titleLogo.src = 'libs/logo.png';
            titleLogo.className = 'title-slide-logo';
            titleLogo.alt = 'Universitas Airlangga Logo';
            slide.insertBefore(titleLogo, slide.firstChild);
          }
          return;
        }
        
        // For all other slides, ensure only ONE logo exists
        const existingLogos = slide.querySelectorAll('.slide-logo');
        
        // If multiple logos exist, remove all and start fresh
        if (existingLogos.length > 1) {
          existingLogos.forEach(logo => logo.remove());
        }
        
        // Check background color
        const bgColor = slide.getAttribute('data-background-color');
        const logoSrc = (bgColor === '#14497F' || bgColor === '#14497f') 
          ? 'libs/logo_white.png' 
          : 'libs/logo.png';
        
        // If exactly one logo exists, just update its source
        if (existingLogos.length === 1) {
          existingLogos[0].src = logoSrc;
        } 
        // If no logo exists, create one
        else if (existingLogos.length === 0) {
          const logo = document.createElement('img');
          logo.src = logoSrc;
          logo.className = 'slide-logo';
          logo.alt = 'Universitas Airlangga Logo';
          slide.appendChild(logo);
        }
      });
    }

    // Initialize on page load
    document.addEventListener('DOMContentLoaded', function() {
      if (typeof Reveal !== 'undefined') {
        Reveal.on('ready', function() {
          manageLogos();
        });
      } else {
        setTimeout(manageLogos, 500);
      }
    });

    // Update when slides change
    if (typeof Reveal !== 'undefined') {
      Reveal.on('slidechanged', function() {
        manageLogos();
      });
    }
    </script>

    <style>
    /* Additional inline styles for logo */
    .reveal .slide-logo {
      position: absolute !important;
      top: -1em !important;  /* Aligns with title */
      right: 15px !important;
      max-height: 80px !important;
      max-width: 200px !important;
      z-index: 100 !important;
      object-fit: contain;
    }

    /* Ensure title slide doesn't have logo overlap */
    .reveal .title-slide {
      padding-right: 220px;
    }

    /* Section title slide styling */
    .reveal section[data-background-color] h1,
    .reveal section[data-background-color] h2 {
      color: white !important;
    }
    </style>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>