project:
  type: website
  output-dir: docs

website:
  title: "Latent Variable Modeling Workshop"
  navbar:
    left:
      - text: "oleh Rizqy Amelia Zein"
        href: https://rameliaz.github.io/
      - icon: github
        href: https://github.com/rameliaz/mg-sem-workshop
    right:
      - text: "Salindia (HTML)"
        menu:
          - text: "Bagian 1"
            href: slides/materi-lvm-1.html
          - text: "Bagian 2"
            href: slides/materi-lvm-2.html
          - text: "Bagian 3"
            href: slides/materi-lvm-3.html
          - text: "Bagian 4"
            href: slides/materi-lvm-4.html
      - text: "Salindia (PDF)"
        menu:
          - text: "Bagian 1"
            href: slides/materi-lvm-1.pdf
          - text: "Bagian 2"
            href: slides/materi-lvm-2.pdf
          - text: "Bagian 3"
            href: slides/materi-lvm-3.pdf
          - text: "Bagian 4"
            href: slides/materi-lvm-4.pdf
      - text: "Dataset"
        menu:
          - text: "Dataset Contoh Korelasi"
            href: corr.jasp
          - text: "Dataset Contoh CFA (*.jasp)"
            href: contoh-cfa.jasp
          - text: "Dataset Contoh CFA (*.csv)"
            href: contoh-cfa.csv
          - text: "Dataset Latihan CFA (*.csv)"
            href: dataset-wave1.csv
      - text: "Survei"
        menu:
          - text: "Evaluasi Workshop"
            href: https://www.soscisurvey.de/invited-talk-feedback/

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    df-print: paged
    highlight-style: tango
